#!/usr/bin/env bash
hugo new site quickstart
cd quickstart
git init
echo "theme = 'ananke'" >> config.toml
hugo new module1_task0/dist/welome.md
---
title: "Welcome to Awesome Inc."
date: 2022-11-20T09:03:20-08:00
draft: true
---
