---
name: module3_task1
run-name: module3_task1
on:
    schedule:
        # * is a special character in YAML so you have to quote this string
        - cron:  '30 5 * * *'
    push:

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup
              run: ./setup.sh
              working-directory: module3_task1

            - name: Build
              run: sudo make build
              working-directory: module3_task1
