---
name: module3_task3
run-name: module3_task3
on: #yamllint disable-line rule:truthy
  push:
    branches:
      - master
    tags:
      - "*"
  schedule:
    - cron: "00 5 * * *"
permissions:
  contents: write
defaults:
  run:
    working-directory: module3_task3
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        run: ./setup.sh

      - name: Build
        run: sudo make build

      - name: Test validation
        id: test
        run: sudo make test

      - name: Package
        if: steps.test.outputs.exit_code == 0
        run: sudo make package

      - name: 1.0.0
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module3_task3/DEPLOY.md
            module3_task3/awesome-website.zip
